import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Swalay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />

      </Head>

      <body className={inter.className} >

        <Navbar />

        <main style={{ padding: "1rem", minHeight: "80vh" }}>
          {/* <section style={{ border: "2px solid green" }}> */}
          <section>
            {children}
          </section>
        </main>

        <div style={{ padding: "1rem"}}>
          <Footer />
        </div >

      </body>
    </html>
  );
}
